// 自動生成 (tools/gen-embedded-ja.py)。手で直さないこと。
//
// 資材 .bundle が見つからない環境(LiveContainer など)でも設定画面が日本語になるよう、
// 日本語の文言だけを本体に持たせる。端末の言語が日本語のときだけ使う。
#import <Foundation/Foundation.h>

static NSString *const kYTMUJAKeys[] = {
    @"ALL_DOWNLOADS",
    @"APPLY",
    @"APPLY_DESC",
    @"APPLY_MESSAGE",
    @"AUDIO",
    @"AV_DEFAULT_MODE",
    @"BACKGROUND_PLAYBACK",
    @"BACKGROUND_PLAYBACK_DESC",
    @"CANCEL",
    @"CLEAR_CACHE",
    @"CLOSE",
    @"DEFAULT",
    @"DELETE",
    @"DELETE_MESSAGE",
    @"DISCORD",
    @"DISCORD_DESC",
    @"DONE",
    @"DONT_RUSH",
    @"DONT_RUSH_DESC",
    @"DONT_STICK_HEADERS",
    @"DONT_STICK_HEADERS_DESC",
    @"DOWNLOADING",
    @"DOWNLOADS",
    @"DOWNLOAD_AUDIO",
    @"DOWNLOAD_AUDIO_DESC",
    @"DOWNLOAD_COVER",
    @"DOWNLOAD_COVER_DESC",
    @"DOWNLOAD_PREMIUM",
    @"EMPTY",
    @"ENABLED",
    @"ENABLED_DESC",
    @"EXPLORE",
    @"FORCE_PREMIUM",
    @"FORCE_PREMIUM_DESC",
    @"FOUND_SEGMENT",
    @"HIDE_CAST_BUTTON",
    @"HIDE_CAST_BUTTON_DESC",
    @"HIDE_DOWNLOADS",
    @"HIDE_EXPLORE",
    @"HIDE_FILTER_BUTTON",
    @"HIDE_FILTER_BUTTON_DESC",
    @"HIDE_HISTORY_BUTTON",
    @"HIDE_HISTORY_BUTTON_DESC",
    @"HIDE_HOME",
    @"HIDE_LIBRARY",
    @"HIDE_SAMPLES",
    @"HOME",
    @"LIBRARY",
    @"LINKS",
    @"LINK_NOT_FOUND",
    @"LOGIN_INFO",
    @"LOW_CONTRAST",
    @"LOW_CONTRAST_DESC",
    @"NAVBAR_SETTINGS",
    @"NO_ADS",
    @"NO_ADS_DESC",
    @"NO_AUTORADIO",
    @"NO_AUTORADIO_DESC",
    @"OLED_DARK_KEYBOARD",
    @"OLED_DARK_KEYBOARD_DESC",
    @"OLED_DARK_THEME",
    @"OLED_DARK_THEME_DESC",
    @"OOPS",
    @"PLAYBACK_RATE_BUTTON",
    @"PLAYBACK_RATE_BUTTON_DESC",
    @"PLAYER_SETTINGS",
    @"PREMIUM_SETTINGS",
    @"PREPARING",
    @"REGIONAL_RESTRICTION",
    @"REMOVE_ALL",
    @"REMOVE_TABBAR_LABELS",
    @"RENAME",
    @"RESTART_FOOTER",
    @"RETRY_LOGIN",
    @"SAMPLES",
    @"SAVED_TO_PHOTOS",
    @"SB_ASK",
    @"SB_BEHAVIOR",
    @"SB_NOTIF_DURATION",
    @"SB_SKIP",
    @"SEEK_BUTTONS",
    @"SEEK_TIME_FOOTER",
    @"SEGMENT_SKIPPED",
    @"SELECTABLE_LYRICS",
    @"SELECTABLE_LYRICS_DESC",
    @"SELECT_ACTION",
    @"SETTINGS",
    @"SHARE_ALL",
    @"SKIP",
    @"SKIP_CONTENT_WARNING",
    @"SKIP_CONTENT_WARNING_DESC",
    @"SKIP_NONMUSIC_PARTS",
    @"SKIP_NONMUSIC_PARTS_DESC",
    @"SOURCE_CODE",
    @"SOURCE_CODE_DESC",
    @"STARTUP_TAB",
    @"TABBAR_SETTINGS",
    @"TAB_SETTINGS",
    @"THEME_SETTINGS",
    @"TWITTER",
    @"TWITTER_DESC",
    @"UNSKIP",
    @"VIDEO",
    @"VOLBAR",
    @"VOLBAR_DESC",
    @"WARNING",
    @"YES",
};

static NSString *const kYTMUJAValues[] = {
    @"保存した音源すべて",
    @"適用",
    @"アプリを終了して変更を適用します",
    @"この操作でYouTube Musicを終了し、変更を適用します。本当にいいですか？",
    @"音楽",
    @"デフォルトの再生モード",
    @"バックグラウンド再生",
    @"バックグラウンド再生を有効化",
    @"キャンセル",
    @"キャッシュを消す",
    @"閉じる",
    @"既定",
    @"削除",
    @"%@ を削除しますか?",
    @"Discordサーバーに参加",
    @"バグの報告と機能のリクエスト",
    @"完了",
    @"曲を再生して取得",
    @"リンクを取り出すために曲の再生が必要です",
    @"見出しを固定しない",
    @"画面の上に貼りつく見出しを、普通にスクロールするようにします",
    @"保存中",
    @"保存済み",
    @"音源を保存",
    @"プレイヤーの YTMUltimate ボタンから音源を保存できるようにします",
    @"ジャケット画像を保存",
    @"プレイヤーの YTMUltimate ボタンからジャケット画像を保存できるようにします",
    @"保存(Premium が必要)",
    @"保存したものがここに並びます",
    @"有効",
    @"プレミアム機能、広告非表示、バックグラウンド再生など",
    @"見つける",
    @"Premium を強制的に有効にする",
    @"Premium の機能を強制的に有効にします。",
    @"本編以外の区間を検出しました",
    @"キャストボタンを非表示",
    @"ナビゲーションバーのキャストボタンを非表示にします",
    @"「保存済み」タブを隠す",
    @"「見つける」タブを隠す",
    @"並べ替えボタンを消す",
    @"ライブラリと保存済みの絞り込みボタンを上部バーから消します",
    @"履歴ボタンを非表示",
    @"ナビゲーションバーの履歴ボタンを非表示にします",
    @"「ホーム」タブを隠す",
    @"「ライブラリ」タブを隠す",
    @"「サンプル」タブを隠す",
    @"ホーム",
    @"ライブラリ",
    @"リンク",
    @"リンクが見つかりません",
    @"Google アカウントにサインインしたあと、アプリの再起動が必要です",
    @"コントラストを下げる",
    @"文字とボタンのコントラストを下げます",
    @"ナビゲーションバーオプション",
    @"広告を非表示",
    @"アプリ内広告を削除",
    @"ラジオを無効化する",
    @"エンドレスミュージック機能を無効化",
    @"有機ELダークキーボード",
    @"有機ELダークキーボードを有効にします",
    @"有機ELダークテーマ",
    @"有機ELダークテーマを有効にします",
    @"問題が起きました",
    @"再生速度ボタンを表示",
    @"再生速度を変更できます",
    @"プレーヤーオプション",
    @"プレミアムオプション",
    @"準備中…",
    @"お住まいの国では YouTube Music が制限されているようです。",
    @"音源をすべて削除",
    @"No tab bar labels",
    @"名前を変更",
    @"変更を適用するためにアプリを再起動",
    @"回避策を有効にしました。",
    @"サンプル",
    @"写真に保存しました",
    @"確認する",
    @"動作",
    @"通知を出す秒数",
    @"スキップ",
    @"前後の曲のボタンを早送り・巻き戻しにする",
    @"送る秒数を選びます",
    @"本編以外の区間をスキップしました",
    @"歌詞のテキスト選択",
    @"歌詞のテキスト選択を有効にします",
    @"動作を選ぶ",
    @"設定",
    @"音源をすべて共有",
    @"スキップ",
    @"コンテンツの警告を飛ばす",
    @"不適切な可能性がある内容の警告を飛ばします",
    @"SponsorBlock",
    @"ミュージックビデオでの音楽以外のセクションをスキップします",
    @"ソースコード",
    @"コードを表示する",
    @"起動時のタブ",
    @"タブバーの設定",
    @"タブの設定",
    @"テーマオプション",
    @"ツイッターで %@ をフォロー",
    @"更新情報を入手する",
    @"スキップを取り消す",
    @"映像",
    @"ボリュームバー",
    @"プレーヤーにボリュームバーを追加する",
    @"警告",
    @"はい",
};

NSString *YTMUEmbeddedJapanese(NSString *key) {
    if (!key) return nil;

    static NSDictionary<NSString *, NSString *> *table = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        NSUInteger n = sizeof(kYTMUJAKeys) / sizeof(kYTMUJAKeys[0]);
        table = [NSDictionary dictionaryWithObjects:kYTMUJAValues forKeys:kYTMUJAKeys count:n];
    });

    return table[key];
}
